name: CI for Main Branch

on:
  push:
    branches:
      - main

jobs:
  prebuild:
    name: Prebuild Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, windows-2019, macos-latest, macos-latest-large, ubuntu-latest]
    timeout-minutes: 30
    steps:
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        name: Setup Dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y g++-multilib gcc-multilib libcups2-dev linux-libc-dev
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v4
      - run: npm i
      - if: ${{ matrix.os == 'macos-latest' }}
        name: Prebuild
        run: |
          npm run apply-patches
          npm run prebuild -- --strip --all --arch arm64 -u ${{ secrets.PREBUILD_TOKEN }}
      - if: ${{ matrix.os == 'windows-2019' }}
        name: Prebuild
        run: |
          npm run apply-patches
          npm run prebuild -- --strip --all --arch ia32 -u ${{ secrets.PREBUILD_TOKEN }}
      - if: |
          ${{ matrix.os != 'macos-latest' &&  matrix.os != 'windows-2019' }}
        name: Prebuild
        run: |
          npm run apply-patches
          npm run prebuild -- --strip --all --arch x64 -u ${{ secrets.PREBUILD_TOKEN }}
